# Generated by Django 5.2.5 on 2025-08-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_url',
            field=models.URLField(help_text='URL of the RSS feed or sitemap', max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(help_text='Base URL of the website', max_length=2048, unique=True),
        ),
    ]
