# Generated by Django 5.2.5 on 2025-08-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_alter_article_url_alter_feed_feed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='additional_feeds',
            field=models.ManyToManyField(blank=True, help_text='Other feeds where this article appeared', related_name='cross_posted_articles', to='feeds.feed'),
        ),
    ]
