# Generated by Django 5.2.5 on 2025-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_article_additional_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='auto_fetch_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic content fetching'),
        ),
        migrations.AddField(
            model_name='website',
            name='fetch_interval_minutes',
            field=models.IntegerField(choices=[(15, 'Every 15 minutes'), (30, 'Every 30 minutes'), (60, 'Every hour'), (120, 'Every 2 hours'), (240, 'Every 4 hours'), (360, 'Every 6 hours'), (720, 'Every 12 hours'), (1440, 'Daily')], default=60, help_text='How often to fetch new content (in minutes)'),
        ),
        migrations.AddField(
            model_name='website',
            name='last_auto_fetch',
            field=models.DateTimeField(blank=True, help_text='Last automatic fetch time', null=True),
        ),
    ]
