# Generated by Django 5.2.5 on 2025-08-17 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_add_scheduling_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_summary', models.TextField(help_text='AI-generated summary')),
                ('topics', models.JSONField(default=list, help_text='List of topics/categories')),
                ('entities', models.JSONField(default=dict, help_text='Named entities (people, orgs, locations)')),
                ('sentiment', models.CharField(default='neutral', help_text='Sentiment: positive/negative/neutral', max_length=20)),
                ('keywords', models.JSONField(default=list, help_text='SEO keywords')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='feeds.article')),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='Original article if this is a duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='feeds.article')),
                ('similar_articles', models.ManyToManyField(blank=True, help_text='Articles with similar content', related_name='similar_to', to='feeds.article')),
            ],
            options={
                'verbose_name_plural': 'Article analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(help_text='Generated content in HTML format')),
                ('summary', models.TextField(blank=True, help_text='Brief summary')),
                ('style', models.CharField(choices=[('news', 'News Article'), ('blog', 'Blog Post'), ('analysis', 'Analysis'), ('summary', 'Summary')], default='news', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('topics', models.JSONField(default=list, help_text='Topics covered')),
                ('media_items', models.JSONField(default=list, help_text='Associated media URLs and captions')),
                ('generation_params', models.JSONField(default=dict, help_text='Parameters used for generation')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_url', models.URLField(blank=True, max_length=2048)),
                ('source_articles', models.ManyToManyField(help_text='Source articles used', related_name='generated_content', to='feeds.article')),
            ],
            options={
                'verbose_name': 'Generated content',
                'verbose_name_plural': 'Generated content',
                'ordering': ['-generated_at'],
            },
        ),
    ]
