# Generated by Django 5.2.5 on 2025-08-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_articleanalysis_generatedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='web_sources',
            field=models.JSONField(default=list, help_text='Web sources used for research'),
        ),
    ]
