# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_add_similarity_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Cluster title describing the event/story', max_length=500)),
                ('description', models.TextField(help_text='Brief description of what this cluster is about')),
                ('event_type', models.CharField(blank=True, help_text='Type of event (breaking news, ongoing story, etc)', max_length=100)),
                ('main_topics', models.JSONField(default=list, help_text='Main topics/themes')),
                ('key_entities', models.JSONField(default=dict, help_text='Key people, orgs, locations')),
                ('earliest_article', models.DateTimeField(blank=True, null=True)),
                ('latest_article', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in this cluster (0-1)')),
                ('source_count', models.IntegerField(default=0, help_text='Number of unique sources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('articles', models.ManyToManyField(related_name='clusters', to='feeds.article')),
            ],
            options={
                'ordering': ['-latest_article', '-source_count'],
            },
        ),
        migrations.AddIndex(
            model_name='articlecluster',
            index=models.Index(fields=['-latest_article', 'is_active'], name='feeds_artic_latest__12a890_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecluster',
            index=models.Index(fields=['-created_at'], name='feeds_artic_created_8b24db_idx'),
        ),
    ]