# Generated by Django 5.2.5 on 2025-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_add_selective_sitemap_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('runtime_seconds', models.FloatField(blank=True, null=True)),
                ('articles_fetched', models.IntegerField(default=0)),
                ('feeds_processed', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['-started_at'], name='feeds_taske_started_3df452_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task_name', '-started_at'], name='feeds_taske_task_na_c10179_idx'),
        ),
    ]