# Generated by Django 5.2.5 on 2025-08-21

from django.db import migrations, models
import django.db.models.deletion


def create_default_project(apps, schema_editor):
    """Create CultureTrend project and assign all existing websites to it."""
    Project = apps.get_model('feeds', 'Project')
    Website = apps.get_model('feeds', 'Website')
    
    # Create CultureTrend project
    culture_trend = Project.objects.create(
        name='CultureTrend',
        slug='culturetrend',
        description='Entertainment and culture news aggregation',
        active=True
    )
    
    # Create ThePitch.news project
    the_pitch = Project.objects.create(
        name='ThePitch.news',
        slug='thepitch-news',
        description='News aggregation project',
        active=True
    )
    
    # Assign all existing websites to CultureTrend
    Website.objects.all().update(project=culture_trend)


def reverse_migration(apps, schema_editor):
    """Remove projects on migration reversal."""
    Project = apps.get_model('feeds', 'Project')
    Project.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_add_task_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='website',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='feeds.project'),
        ),
        migrations.RunPython(create_default_project, reverse_migration),
        migrations.AlterField(
            model_name='website',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='feeds.project'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=2048, help_text='Base URL of the website'),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('project', 'url')},
        ),
    ]